# Generated by Django 4.1.5 on 2024-08-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpiId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upi_id", models.TextField(blank=True)),
                ("usage_count", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
