# Generated by Django 4.1.5 on 2024-08-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_upiid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upiid",
            name="usage_count",
            field=models.IntegerField(default=0),
        ),
    ]
